# d10: meta fields and the prose answer (identical in research_out.json and the SDK output)
TITLE = "Prior-Art Check for a Few-Prompt Safety Score"

LAYMAN_SUMMARY = ("Verifies every published claim and number a new few-prompt activation-based safety metric would compare "
                  "against (AMS scanner r=-0.546, 98.2%-AUROC latent probes, Arditi refusal direction, Qwen3/Llama/Gemma "
                  "checkpoint zoo), and checks whether the idea is still new as of 19 Sep 2026.")

SUMMARY = ("Research artifact that pins down (1) which related-work claims in the hypothesis are real and what numbers they "
           "actually have, (2) algorithm-level specs for every baseline the experiment must re-implement (Arditi diff-of-means "
           "refusal direction + weight orthogonalization; AMS-style scanner sigma; supervised latent probe; refusal-template "
           "log-prob; knowledge-side probe control), (3) the exact non-gated HuggingFace checkpoint IDs for a Qwen3 "
           "base/instruct/abliterated zoo (with Llama-3.2/Gemma gated and mirror fallbacks), and (4) a dated saturation "
           "verdict. Key findings: all seven hypothesis citations resolve to real papers, but three characterizations are "
           "wrong (Arditi uses difference-in-means with NO PCA and 128+32 prompts per class, not 74/54; the flat ~0.98 "
           "abliteration-insensitive probe claim belongs to Llorente-Saguer 2604.18901 (+-0.003 AUROC) and LatentBiopsy "
           "2603.27412 (<=0.015), not to Khatri 2609.19472; the knowledge-action 98.2/45.1 numbers belong to Basu 2603.18353); "
           "the AMS scanner r = -0.546 is UNVERIFIED (paper PDF inaccessible) and must be replaced by an in-zoo comparison; "
           "RAS/SafeVec (2606.25750) already occupies the label-rich per-model refusal-alignment-score lane, leaving the "
           "label-free few-prompt per-model refusal-RATE prediction slot thin but open. The zoo is feasible: Qwen3-0.6B/1.7B/4B "
           "(conversational) + -Base variants + huihui-ai/mlabonne abliterated 4B exist non-gated under the sizes checked; "
           "community-abliterated Gemma-2-2B exists only in GGUF (self-abliterate or swap family); Qwen3 thinking mode defaults "
           "on (enable_thinking=True), forcing a readout-position decision.")

PROSE_ANSWER = (
"I verified the hypothesis's related-works list against primary sources on 2026-09-19. All seven named works exist, but "
"several characterizations in the hypothesis are wrong, and one headline number could not be verified.\n\n"
"1. AMS scanner (Messenger 2026) is real: Google Open Source Blog announcement 2026-04-27 [1], Zenodo paper 19501951 [2], and "
"GitHub GoogleCloudPlatform/activation-model-scanner [3], built on the AASE paired-contrastive-probe methodology [4]. It "
"measures harmful-vs-benign direction separation in standard deviations (4-8 sigma), validated on 14 model configurations "
"across Llama/Gemma/Qwen and 3 quantization levels [2], with per-class sigma values 3.8-8.4 (instruction-tuned), 1.1-1.3 "
"(uncensored), 3.33 (abliterated), 0.69 (base) and thresholds PASS >3.5 / WARNING 2.0-3.5 / CRITICAL <2.0 [1, 3]. The claimed "
"scanner-vs-behavioral-compliance correlation r = -0.546 is NOT in the blog, the README, or the Zenodo abstract, and the "
"paper PDF is blocked (HTTP 403); it must be treated as UNVERIFIED and replaced by an in-zoo scanner-vs-behavior rho.\n\n"
"2. Arditi et al. 2024 (arXiv 2406.11717, NeurIPS 2024) [5, 6, 24] is the B1 baseline. The direction is DIFFERENCE-IN-MEANS "
"over residual-stream activations at post-instruction token positions (mostly the last user token), NOT PCA: a full-text grep "
"for 'PCA|principal component' returns zero matches [6]. Contrast sets are harmful (AdvBench, MaliciousInstruct, TDC2023, "
"HarmBench) and harmless (Alpaca) with 128 train + 32 validation each [6], not the hypothesis's 74/54. Single-vector selection "
"uses bypass/induce scores with kl_score < 0.1 and layer fraction < 0.8L; example choices: Llama-2 7B i*=-1 l*=14/32, "
"Llama-3 8B i*=-5 l*=12/32 [6]. Weight orthogonalization (abliteration) is W' = W - rhat*rhat^T*W applied to embedding, "
"positional-embedding, attention-out and MLP-out matrices plus output biases [6]. Code: github.com/andyrdt/refusal_direction "
"[7] and Sumandora/remove-refusals-with-transformers [8]. Orthogonalized Llama-2 7B reaches ASR 22.6 (79.9 without system "
"prompt) [6].\n\n"
"3. Khatri 2026 'Safety Beyond the Interface' (arXiv 2609.19472, IEEE DSN-W 2026) exists [9] but is a per-prompt latent-state "
"harm detector (12.6M-param MLP probes on LLaMA-3.1-8B, F1 99/83/84 on WildJailbreak/BeaverTails/AEGIS 2.0); it contains NO "
"abliteration experiments and NO 0.98 figure, and no reproducibility study was found. The flat ~0.98-across-abliteration claim "
"belongs to Llorente-Saguer: supervised harm-direction probes reach AUROC 0.982 and stay within +-0.003 AUROC of the "
"instruction-tuned variant after abliteration across 12 models and 4 families [11], and LatentBiopsy's training-free angular "
"score stays within 0.015 [12].\n\n"
"4. The knowledge-action gap numbers 98.2% AUROC vs 45.1% output sensitivity (53-percentage-point gap), 3,695 significant SAE "
"features, 400 physician-adjudicated vignettes (144 hazards), Qwen2.5-7B-Instruct + Steerling-8B all verify verbatim in Basu "
"et al., arXiv 2603.18353 [10]; this is ONE domain (clinical) and ONE family, so zoo-wide flatness stays a claim to test.\n\n"
"5. Hildebrant (arXiv 2501.08145, six models, PCA/t-SNE/UMAP, no scalar metric) [16] and Jiang (arXiv 2606.08044, dissociated "
"models, LVS 2.5-3.1x, latent attacks 54-86% vs 3-48%) [17] verify as characterized, and the refusal-tokens paper (arXiv "
"2412.06748) [18] exists but is a training-time calibration mechanism, not a detection baseline.\n\n"
"6. Saturation (dated 2026-09-19, arXiv API + web): the lane is dense but the specific slot is open. RAS/SafeVec (arXiv "
"2606.25750) [14, 15] already computes a calibrated 0-100 per-model refusal-alignment score that separates "
"aligned/uncensored/abliterated on Llama/Gemma/Qwen and tracks attack success rate - but it needs a reference aligned model "
"and three LABELED prompt sets. LatentBiopsy (arXiv 2603.27412) [12] is label-free but a per-prompt detector. Hurtado's "
"two-signal abliteration audit (arXiv 2607.01854, AUROC 0.95) [13] is a per-model abliteration triage. 'Refusal Before "
"Decoding' (2605.28553) [19] shows refusal is linearly decodable at every block. Joad et al. (EMNLP 2026, 2602.02132) [20] "
"counters single-direction readings: directions differ per refusal category, changing HOW not WHETHER the model refuses. "
"Nearest-prior-art IDs verified: RepE 2310.01405, ITI 2306.03341, Tuned Lens 2303.08112, Patchscopes 2401.06102, HarmBench "
"2402.04249, WMDP 2403.03218, Circuit Breakers 2406.04313, LAT 2403.05030 [23].\n\n"
"7. HuggingFace audit (live API, 2026-09-19): Qwen/Qwen3-0.6B/1.7B/4B are the conversational (instruct) checkpoints "
"(standalone '-Instruct' IDs return 401), Qwen/Qwen3-1.7B-Base and Qwen/Qwen3-4B-Base are the base members, "
"Qwen/Qwen3-4B-Instruct-2507 is the refresh, and Qwen3.5-0.8B/4B exist as newer families [22]. Abliterated safetensors "
"candidates exist non-gated: huihui-ai/Huihui-Qwen3-4B-Instruct-2507-abliterated (8.0GB, template in a separate "
"chat_template.jinja), mlabonne/Qwen3-4B-abliterated (16.1GB, oversize), huihui-ai/Llama-3.2-3B-Instruct-abliterated, "
"mylesgoose/Llama-3.2-1B-Instruct-abliterated, Goekdeniz-Guelmez/Josiefied-Qwen2.5-1.5B-Instruct-abliterated-v1; no "
"community-abliterated Qwen3-0.6B/1.7B or safetensors Gemma-2-2B exists (bartowski/gemma-2-2b-it-abliterated-GGUF is "
"GGUF-only) -> self-abliterate or swap family. meta-llama/Llama-3.2 and google/gemma are gated 'manual'; non-gated unsloth "
"mirrors exist for all of them [22]. Qwen3 README confirms enable_thinking=True is the default [21], so the first generated "
"token is a think/control token and position-0 refusal log-probs need thinking disabled or the readout shifted.\n\n"
"Confidence: high for every VERIFIED claim (primary sources fetched same-day); the single UNVERIFIED item is the AMS "
"r = -0.546 (would be resolved by reading the Zenodo PDF). Novelty verdict: the label-free, few-prompt, per-model behavioral "
"refusal-RATE predictor slot is THIN/OPEN as of 2026-09-19, but the knowledge-action tri-partition phenomenon is already "
"documented and RAS/LatentBiopsy are close neighbors that the experiment must benchmark against."
)